### ISSUE TITLE
Some Issues with the Rest API

### ISSUE THREAD

**Issue by explodingcamera** [fantasymarket/fantasymarket-api#25]
Sometimes we get malformed responses, since there are returns missing after calling responses.ErrorResponses (e.g in https://github.com/fantasymarket/fantasymarket-api/blob/4056a6e2308c092d038ff46fc16e6b70ba3825f9/api/v1/events.go#L8-L18 and in nearly all other files in `api/v1`).

https://github.com/fantasymarket/fantasymarket-api/blob/4056a6e2308c092d038ff46fc16e6b70ba3825f9/api/v1/user.go#L16-L18
Also here, we're returning internal errors to our end-users which might result in security issues.

@Arthlight could you have a look at these? :eyes:

**Comment by Arthlight** [comment]
Thanks for pointing it out explodingcamera, I will address these issues shortly!
